[Configuration]
# Nombre de groupes à former
nombre_groupes = 8

# Taille standard des groupes
taille_groupes = 32

# Taille maximale autorisée pour les groupes
taille_max_groupes = 35

# Liste des UEX disponibles (séparées par des virgules, en majuscules)
liste_uex = BIO303,BIO304,BIO305
